# .github/workflows/deploy-mlflow.yaml
name: Deploy to Maroon Bells

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-maroonbells:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: 'true'

      - name: Disable SSH host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone homelab-k3s repo on Maroon Bells
        run: |
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone ssh://${{ secrets.SERVER_USER }}@${{ secrets.MAROONBELLS_HOST }}:/home/${{ secrets.SERVER_USER }}/homelab-k3s.git homelab-k3s

      - name: Copy K8s manifests to homelab-k3s repo
        run: |
          # Create target directory if it doesn't exist
          mkdir -p homelab-k3s/clusters/homelab
          
          # Copy all deployment files to homelab-k3s repo
          cp *.yaml homelab-k3s/clusters/homelab/
          
          # Copy flux directory if needed
          if [ -d "flux" ]; then
            cp -r flux homelab-k3s/clusters/homelab/
          fi

      - name: Commit and Push Changes to Maroon Bells
        run: |
          cd homelab-k3s
          git config user.email "ci-bot@example.com"
          git config user.name "CI Bot"
          git add clusters/homelab/
          git commit -m "Update homelab manifests from GitHub Actions"
          git push origin main
